# Generated by Django 4.1.4 on 2022-12-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spiderstarturl',
            unique_together={('order', 'spider', 'url')},
        ),
    ]
