# Generated by Django 4.1.4 on 2022-12-30 19:04

import DomeApp.models.spider
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DomeApp', '0003_spider_spy'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='spider',
            name='spy',
            field=models.TextField(choices=[('spy', 'Default')], default='spy'),
        ),
        migrations.CreateModel(
            name='SpiderCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('args', models.JSONField(default=list)),
                ('return_code', models.IntegerField(blank=True, null=True)),
                ('stdout', models.FileField(upload_to=DomeApp.models.spider.spider_call_upload_to)),
                ('stderr', models.FileField(upload_to=DomeApp.models.spider.spider_call_upload_to)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DomeApp.spider')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
