# Generated by Django 4.1.4 on 2023-01-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DomeApp', '0005_spiderprocess_pipeline_spiderprocessrelation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spiderprocess',
            unique_together={('name', 'pipeline')},
        ),
        migrations.AddField(
            model_name='spiderprocess',
            name='params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.RemoveField(
            model_name='spiderprocess',
            name='spider',
        ),
    ]
