# Generated by Django 4.1.4 on 2023-01-04 23:33

from django.db import migrations, models
import django.db.models.deletion
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DomeApp', '0006_alter_spiderprocess_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DomeApp.spiderauthentication'),
        ),
        migrations.AlterField(
            model_name='spiderauthentication',
            name='data',
            field=mirage.fields.EncryptedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='spiderresult',
            name='data',
            field=mirage.fields.EncryptedJSONField(default=dict),
        ),
    ]
